research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

coding_task:
  description: >
    Write a Python script to the best of your capabilities for the {question}
  expected_output: >
    Output the script for the code generated.
    The script should be well-documented and easy to understand.
    The script should be able to handle potential errors and exceptions gracefully.
  agent: coder
  output_file: data/code.py
  
  input_data:
reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
  output_file: data/report.md
